---
title: "Meetings summary"
author: "Pablo Recio"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
    code_folding: hide
    number_sections: no
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results = 'asis' , eval = TRUE)
options(digits=2)
```

## **Meeting 29/08/2022**


<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

* Personality tests: which four objects for neophobia/neophilia tests // How to divide the terrarium in squares  
  <span style="color: darkblue;">
  + Check for objects in the lab. Think if we should use prey (same as in  Ch 2) as the novel stimuli  
  + To “square” the terraria we can use paper with glue underneath (we will have to buy it) or use double/side tape +sand on the edges (+ walls?) 
  </span>
* Spatial task: size of the terraria we can use for that // Should we build some kind of predator model instead of chasing them directly?  
  <span style="color: darkblue;">
  + Communal terraria can be used for the spatial learning task. Need to:  
    - Check if the cameras can cover all the space  
    - Measure them and buy more: reject shop (pick up)  
  + Chasing the lizards may be fine but I must be blind to the treatment of the lizard; by, e.g., Dalton giving lizards new identities and keeping record of it  
  </span>
* Visual-reversal tasks: type of cardboards/stimuli employ: hue or colour? Should we use a spectrophotometer to estimate it?  
  <span style="color: darkblue;">
  + Use different colours instead of just different brightness  
  + Measure with spectrophotometer (ask Megan/Martin/Kate Anderson) or buy specific paints that come with this type of information  
  </span>
* Cue perception tests: preys, type and how many // containers
  <span style="color: darkblue;">
  + Possible types of prey: flour beetles, seed beetles, wax worms, mealworms, etc.; several possibilities  
  + Randomize and counterbalance order of presentation or keep the same order for every lizard  
  </span>
* Chemicals needed for Oroboros  
  <span style="color: darkblue;">
  + Review Krumschnabel et al., 2015 – Write Karine  
  </span>
* Chapter 3 – ideas HPA measures  
  <span style="color: darkblue;">
  + Measure only baseline levels (by terminal sampling) and relate to personality <span style="color: lightgreen;"> ACCEPTED  </span>
  + Measure baseline and after-stressor in different individuals to see the effect of treatment and then compare these results to the effect of treatment on personality (is average “reactivity” different according to treatment? How does it relate with the effect of treatment on personality?) <span style="color: lightgreen;"> ACCEPTED  </span>  
  + Employ CORT and see changes in behaviour; what the question will totally change <span style="color: darkred;"> DISCARDED  </span>
  + See the effect of “chronic stress” and how is linked to personality. In this sense, I will measure personality of lizards first and then I will submit them to chronic stress for a period of time and see if there is an effect on body condition, growth, immune response?, or other traits. In this case, I will need to increase sample size. Basically, it would be similar to the CORT experiment I proposed at the beginning but without needing to validate the process (more realistic too?)  <span style="color: darkred;"> DISCARDED - Need for an amendment of Ethical permissions + body condition and growth may not change in lab conditions  </span> 
  +	Forget about this experiment and do something like in Chapter 4 but with numerical discrimination instead of learning (is the use of numeric or continuous cues related to personality as is learning?). <span style="color: lightgreen;"> ACCEPTED - Can be done as an aside project (maybe another Chapter); develop </span> 
  </span>
</details>

<details>
  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Prepare Material list (review labs and see what we need)
  + Prepare list of chemicals needed (WRITE KARINE)
  + Check CCTV system if we aim to buy more
* Brain anatomy (maps from Dan)
  + See maps from Dan
  + Ask him for a virtual meeting where & dissect a brain
  + How to kill lizards?
* Learn how to use Rmarkdown and git hub
	+ Review codes Dan sent
	+ Create new document with meetings info and organization, and Chapters
* Start metanalysis
	+ Create search terms
	+ Familiarize with RAYYAN
* Analyses learning
	+ Create code
</details>

</details>

## **Meeting 12/09/2022**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* Prepare Material list  
  + ~~Review labs and see what we need~~  
  + ~~Prepare list of chemicals needed ([WRITE KARINE](file:///Users/u7409838/Library/CloudStorage/OneDrive-AustralianNationalUniversity/GitHub/Thesis/Meetings/Meeting-Oroboros.html))~~
  + Check CCTV system if we aim to buy more
* Brain anatomy (maps from Dan)
  + ~~See maps from Dan~~
  + Ask him for a virtual meeting where & dissect a brain
  + How to kill lizards?
* Learn how to use Rmarkdown and git hub
	+ ~~Review codes Dan sent~~
	+ Create new ~~document with meetings info and organization~~, and Chapters
* Start metanalysis
	+ ~~Create search terms~~
	+ ~~Familiarize with RAYYAN~~
* Analyses learning
	+ Create code

</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

* [Material needed](https://github.com/Pablo-Recio/Meetings/blob/main/Material/Material-list.html)  
* Discuss decision tree  
* Discuss Oroboros methods based on the assumption that sample is not going to be enough  
  + If each region weights enough:  
    - Half of the lizards tested for respiration and ATP synthesis, half for ROS (one machine per lizard, each chamber per each region)  <span style="color: red"> - **X** </span>  
    - For each lizard, we will measure ROS of one region and ATP of the other in a randomize way <span style="color: green"> - **V** </span>  
  + If weight per regions is not enough:
    - Pool different regions and measure both respiration and ROS - 3 lizard per measurement = 24 lizards per treatment so we obtain 8 measures of ROS and 8 of respiration per treatment <span style="color: green"> - **V** </span>  
    - Find other ways to measure ROS and use Oroboros only for respiration (homogenates of tissue may involve less mitochondrial loss)
</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Prepare Material list  
  + Check CCTV system if we aim to buy more  
  + Prepare a budget and buy anything necessary
  + Check material necessary for brain dissection and HPA axis reactivity
* Prepare terrariums for spatial tasks and do some trials  
* Brain anatomy (maps from Dan)  
  + Ask him for a virtual meeting where & dissect a brain  
  + How to kill lizards?  
* Analyses learning  
	+ Create code  
* Check studies using Oroboros in lizards
* Learn how to use Rmarkdown and git hub
	+ Create new document with Chapters and Compiled references  
* Meta-analysis  
  + Refine search  
  + Decision tree  
  + Check 100 papers to see how many are useful (RAYYAN)  

</details>

## **Meeting 26/09/2022**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* Prepare [Material list]()  
  + ~~Check CCTV system if we aim to buy more~~  
  + ~~Prepare a budget~~ and buy anything necessary  
    <span style="color: green"> - Already bought: brush (2), Double-side tape (600 m) and normal tape (600 m) from Riotsotores; and contacted with National Storages for the [terraria](https://nationalstorage.com.au/online-shop/product/35l-plastic-storage-container-qty-2/) </span>  
  + Check ~~material necessary for brain dissection~~ and HPA axis reactivity
* Prepare terrariums for spatial tasks and do some trials  
* Brain anatomy (maps from Dan)  
  + ~~Ask him for a virtual meeting where & dissect a brain~~  
  + ~~How to kill lizards?~~ - <span style="color: blue"> Sodium pentobarbital would work with lizards as it will not cross the blood-brain barrier </span>  
* Analyses learning  
	+ Create code  
* ~~Check studies using Oroboros in lizards~~
* Learn how to use Rmarkdown and git hub
	+ Create new document with Chapters and Compiled references  
* Meta-analysis  
  + ~~Refine search~~  
  + ~~Decision tree~~
    - ~~Refine decision tree~~
    - ~~Define learning and other concepts~~
  + ~~Check 100 papers to see how many are useful (RAYYAN)~~  
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

* Buy terraria
* Material needed for measuring mass of different regions in the brain:
  + Dissection material (ready/almost ready)
  + Dissection scope (already in Megan's lab)
  + Balance
  + Eppendorfs, gradients and marker
  + Formalin 10%
* Check where are the 'feeders' for visual learning
* Learn how to insert websites on markdown properly

</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Prepare [Material list]()  
  + Check material necessary for HPA axis reactivity (Ondi)  
  + Get ready the material for measuring brain mass  
* Meta-analysis  
  + Share database with other collaborators and see consistency in 100 papers  
* Practice brain dissections and help obtaining blood samples for CORT analyses  
* Learn how to use Rmarkdown and git hub  
	+ Create new document with Chapters and Compiled references  
* Check studies using Oroboros in zebra fish  
* Prepare terrariums for spatial tasks and do some trials  
* Analyses learning  
	+ Create code  



</details>

</details>


## **Meeting 10/10/2022**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Ethics application~~
* Prepare [Material list]()  
  + ~~Check material necessary for HPA axis reactivity (Ondi)~~  
    <span style="color: green"> Nothing needed now, better to buy everything one or two months before experiments as kits may have an unknown expiry date and usually arrive fast </span>  
  + Get ready the material for measuring brain mass  
* Meta-analysis  
  + ~~Share database with other collaborators and see consistency in 100 papers~~  
* Practice brain dissections and <span style="color: red"> ~~obtaining blood samples for CORT analyses~~ </span>   
* Learn how to use Rmarkdown and git hub  
	+ Create new document with Chapters and Compiled references  
* ~~Check studies using Oroboros in zebra fish~~  
* Prepare terrariums for spatial tasks and do some trials  
* Analyses learning  
	+ Create code  

  
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

* Material: [spatula](https://www.sigmaaldrich.com/AU/en/product/aldrich/z193208)  
* CT scanner meeting   
<span style="color: green">
    - Tissue must not move. They have standarize methods to avoid that
    - We need to stain the brain - <span style="color: blue"> Ask Dan Hoops (Paul Cooper) about techniques valid for both CT scanner and light microscopy </span>
    - They can make the statistical analysis or show me; both is expensive and slow
    - After seeing the tubes, I estimate 10-15, although we may need to do some pre-trials to see the resolution we need
</span>  
* Oroboros zebra fish studies  
<span style="color: green">
    - Papers pooling tissue from different individuals, without information of mass of tissue or tissue mass > 10 mg  
    - Is there really a possibility to increase Oroboros accuracy?  
    - Backup plans:  
      + Slides  
      + Pool samples (effect of treatment)  
      + Use other methods (at least initially) to just measure ATP and ROS (base of my premises)  
</span>
* Ethics application

</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Finish Ethics application
* Learn how to use Rmarkdown and git hub  
	+ Create new document with Chapters and Compiled references  
* Prepare terrariums for spatial tasks and do some trials  
* Analyses learning  
	+ Create code  
* Practice brain dissections

</details>

</details>

## **Meeting 07/11/2022**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Finish Ethics application~~  
* ~~Organize enclosures~~  
* ~~Prepare protocols and buy chemicals for Oroboros~~  
* Learn how to use Rmarkdown and git hub  
	+ Create new document with Chapters  
* Prepare terrariums for spatial tasks and do some trials  
* Analyses learning  
	+ Create code  
* Practice brain dissections  

  
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

* Plans for brains



</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Finish Ethics application  
* Compile all references and notes:  
  + Prepare HDR conference presentation (23/11) | Practice talk on next lab meeting (16/11)  
	+ Create new document with Chapters  
* Meta-analysis:
  + See and compile Results of first screening  
  + Improve definitions of CORT and "stressor"
  + Re-screening the previous abstracts with the new criteria
  + Go through 100 abstracts and send everything to the rest of collaborators to do the same  
* Prepare terrariums for spatial tasks and do some trials  
* Analyses learning  
	+ Create code  
* Practice brain dissections

</details>

## **Meeting 21/11/2022**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Finish Ethics application~~  
* Compile all references and notes:  
  + ~~Prepare HDR conference presentation (23/11) | Practice talk on next lab meeting (16/11)~~  
	+ Create new document with Chapters  
* Meta-analysis:
  + ~~See and compile Results of first screening~~  
  + ~~Improve definitions of CORT and "stressor"~~
  + ~~Re-screening the previous abstracts with the new criteria~~
  + ~~Go through 100 abstracts and send everything to the rest of collaborators to do the same~~  
* Prepare terrariums for spatial tasks and do some trials  
* Analyses learning  
	+ Create code  
* Practice brain dissections

  
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

* Learning how to introduce references in rmarkdown  
* Change hour/day meetings  


</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Poster for ANZSCPB and talk for AES
* Compile all references and notes:  
 	+ Create new document with Chapters  
* Experiments:  
  + Search/order feeders for associative and reversal learning  
  + Prepare terrariums for spatial tasks and do some trials  
* Analyses learning  
	+ Create code  
* Practice brain dissections  

</details>

## **Meeting 05/12/2022**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Poster for ANZSCPB and talk for AES~~  
* ~~Review processes Oroboros~~  
* Screening papers Ondi meta-analysis
* Compile all references and notes:  
 	+ Create new document with Chapters  
* Experiments:  
  + Search/order feeders for associative and reversal learning  
  + Prepare terrariums for spatial tasks  
* Analyses learning  
	+ Create code  
* Practice brain dissections  

  
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

* Poster and talk  
* Feeders  

</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Conferences
* Screening papers Ondi meta-analysis
* Compile all references and notes:  
 	+ Create new document with Chapters  
* Experiments:  
  + Search/order feeders for associative and reversal learning  
  + Prepare terrariums for spatial tasks  
* Analyses learning  
	+ Create code  
* Practice brain dissections  


</details>

## **Meeting 15/01/2023**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Lab work~~
* ~~Conferences~~
* ~~Screening papers Ondi meta-analysis~~
* Compile all references and notes:  
 	+ Create new document with Chapters  
* Experiments:  
  + Search/order feeders for associative and reversal learning  
  + Prepare terrariums for spatial tasks  
* Analyses learning  
	+ Create code  
* Practice brain dissections  
  
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

* How to proceed with experiments:  
  + [Plans Ch 3 & 4](./Ch3&4.png)  
  + [Plans Ch 5](./Ch5.png)  
  
</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Lab work  
  + Egg&Baby checking  
  + Build outdoor enclosures  
  + Condense babies  
  + "Improve encloures"  
    - Create a database with the clutches produced per enclosure  
    - See which enclosures are "less productive" and check them  
    - Check other enclosures with more than 6 ind  
    - Replace old males with young males  
* Ondi meta-analysis:  
  + Add pdfs of included papers  
  + Review full texts of Maybes  
  + Help with mitochondrial parameters  
* Compile all references and notes:  
 	+ Create new document with Chapters  
 	+ Help with mitochondrial parameters (Ondi's meta-analysis)  
* Experiments:  
  + Prepare feeders for associative and reversal learning  
* Annual Report  
* Analyses learning  
	+ Create code  
* Practice brain dissections  


</details>

## **Meeting 22/01/2023**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* Lab work  
  + Egg&Baby checking  
  + Build outdoor enclosures  
  + Condense babies  
  + Replace old males with young males in breeding enclosures  
* Ondi meta-analysis:  
  + Add pdfs of included papers  
  + Review full texts of Maybes  
  + Help with mitochondrial parameters  
* Compile all references and notes:  
 	+ Create new document with Chapters  
 	+ Help with mitochondrial parameters (Ondi's meta-analysis)  
* Experiments:  
  + Prepare feeders for associative and reversal learning:  
    - ~~Prepare a prototype~~  
    - Cut the feeders (workshop)  
    - ~~Buy Petri dishes~~  
    - Paint petri dishes  
* Annual Report  
* Analyses learning  
	+ Create code  
* Practice brain dissections
* Compile all references and notes:  
 	+ Create new document with Chapters  
 
  
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

  
  
</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Lab work  
  + Egg&Baby checking  
  + Build outdoor enclosures  
  + Condense babies  
  + Replace old males with young males in breeding enclosures  
* Ondi meta-analysis:  
  + Add pdfs of included papers  
  + Review full texts of Maybes  
  + Help with mitochondrial parameters  
* Compile all references and notes:  
 	+ Create new document with Chapters  
 	+ Help with mitochondrial parameters (Ondi's meta-analysis)  
* Experiments:  
  + Prepare feeders for associative and reversal learning:  
    - Cut the feeders (workshop)  
    - Paint petri dishes  
* Annual Report  
* Analyses learning  
	+ Create code  
* Practice brain dissections
* Compile all references and notes:  
 	+ Create new document with Chapters 


</details>
## **Meeting 06/02/2023**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* Lab work  
  + Egg&Baby checking  
  + Build outdoor enclosures  
  + Condense babies  
  + Replace old males with young males in breeding enclosures  
* Ondi meta-analysis:  
  + Add pdfs of included papers  
  + Review full texts of Maybes  
  + Help with mitochondrial parameters  
* Experiments:  
  + Prepare feeders for associative and reversal learning:  
    - Cut the feeders (workshop)  
    - Paint petri dishes  
* Compile all references and notes:  
 	+ Create new document with Chapters  
 	+ Help with mitochondrial parameters (Ondi's meta-analysis)  
* Annual Report  
* Analyses learning  
	+ Create code  
* Practice brain dissections
* Compile all references and notes:  
 	+ Create new document with Chapters   
 
  
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

  [New plans Ch4](./Ch3&4_bis.png)   
  
</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Lab work  
  + Egg&Baby checking  
  + Build outdoor enclosures  
  + Condense babies  
  + Replace old males with young males in breeding enclosures  
* Ondi meta-analysis:  
  + Add pdfs of included papers  
  + Review full texts of Maybes  
  + Help with mitochondrial parameters  
* Experiments:  
  + Prepare feeders for associative and reversal learning:  
    - Cut the feeders (workshop)  
    - Paint petri dishes  
* Annual Report  
* Analyses learning  
	+ Create code  
* Practice brain dissections
* Compile all references and notes:  
 	+ Create new document with Chapters 


</details>
## **Meeting 30/05/2023**
<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

 * Lab work  
  + ~~Egg&Baby checking~~  
  + ~~Build outdoor enclosures~~  
  + ~~Condense babies~~  
  + Replace old males with young males in breeding enclosures  
* Ondi meta-analysis:  
  + ~~Add pdfs of included papers~~  
  + ~~Review full texts of Maybes~~  
  + Help with mitochondrial parameters  
* Experiments:  
  + ~~Prepare feeders for associative and reversal learning:~~  
    - ~~Cut the feeders (workshop)~~  
    - ~~Paint petri dishes~~  
* ~~Annual Report~~  
* Analyses learning  
	+ Create code  
* Practice brain dissections
* Compile all references and notes:  
 	+ Create new document with Chapters 
 
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

Plans Chapters 2 and 4  
Basile
  
</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Basile's dissertation
  + Help with Introduction  
  + Finish Methods and Supp material  
  + Check Results and Discussion  
* Experiments:
  + Trials reversal learning  
  + Trials personality  
  + Code for learning experiments  
  + Methods of learning experiments  
* Ondi's meta-analysis:  
  + Help with mitochondrial parameters
  + Extract data
* Compile all references and notes:  
 	+ Create new document with Chapters  
 	+ Help with mitochondrial parameters (Ondi's meta-analysis)  
* Practice brain dissections & make homogenates for flow cytometre

</details>  

</details>



## **Meeting 23/06/2023**
<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

 * ~~Basile's dissertation~~
  + ~~Help with Introduction~~
  + ~~Finish Methods and Supp material~~
  + ~~Check Results and Discussion~~
* Experiments:
  + Trials reversal learning  
  + ~~Trials personality~~  
  + Code for learning experiments  
  + Methods of learning experiments  
* Ondi's meta-analysis:  
  + Help with mitochondrial parameters
  + Extract data
* Compile all references and notes:  
 	+ Create new document with Chapters  
 	+ Help with mitochondrial parameters (Ondi's meta-analysis)  
* ~~Practice brain dissections & make homogenates for flow cytometre~~
 
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

General
  
</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Experiments:
  + Trials reversal learning  
  + Check analysis personality  
  + Code for personality and learning  
  + Methods and Introduction of learning experiments  
  + Program stressor experiment (write "Protocol")

* Ondi's meta-analysis:  
  + Help with mitochondrial parameters
  + Extract data
* Compile all references and notes:  
 	+ Create new document with Chapters  
 	+ Help with mitochondrial parameters (Ondi's meta-analysis)  
* Practice brain dissections & make homogenates for flow cytometre

</details>  

</details>

## **Meeting 10/07/2023**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* Experiments:
  + ~~Trials reversal learning~~  
  + Check analysis personality  
  + Code for personality and learning  
  + Methods and Introduction of learning experiments  
  + ~~Program stressor experiment (write "Protocol")~~  

* Ondi's meta-analysis:  
  + Help with mitochondrial parameters
  + Extract data
* Compile all references and notes:  
 	+ Create new document with Chapters  
 	+ Help with mitochondrial parameters (Ondi's meta-analysis)  
* ~~Practice brain dissections & make homogenates for flow cytometre~~
 
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

Plan experiment stressor
  
</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Experiments:  
  + Stressor experiment  
  + Check analysis personality  
  + Code for personality and learning  
  + Methods and Introduction of learning experiments  

* Ondi's meta-analysis:  
  + Help with mitochondrial parameters
  + Extract data
* Compile all references and notes:  
 	+ Create new document with Chapters  
 	+ Help with mitochondrial parameters (Ondi's meta-analysis)  
* Practice brain dissections & make homogenates for flow cytometre

</details>  

</details>

## **Meeting 15/12/2023**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* Experiments:  
  + ~~Stressor experiment~~  
  + Check analysis personality  
  + Code for personality and learning  
  + ~~Methods and~~ Introduction ~~of learning experiments~~  
* Ondi's meta-analysis:  
  + Help with mitochondrial parameters
  + Extract data
* Compile all references and notes:  
 	+ Create new document with Chapters  
 	+ Help with mitochondrial parameters (Ondi's meta-analysis)  
* ~~Practice brain dissections & make homogenates for flow cytometre~~
* ~~Finish prey discrimination experiments~~
* ~~Analyse some results of learning and stressor experiments~~
* ~~Talks for HDR, ASH, and ANZSCPB conferences~~
* ~~Start collecting eggs~~

 
</details>

<details>
  <summary style=font-size:16px>*Things covered during meeting*</summary>

* Numerical discrimination protocols - Talk with Martin about how to program the tablets?  
* Do we need more _Lampropholis_ from Sydney?  

</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Improve code of learning and 'stressor'  
* Have a first draft of the asso-rev learning paper  
* Continue collecting eggs for future experiments  
* Start preparing spatial learning and numerical discrimination protocols  
  + Print maze for spa-learning  
  + Check tablets and video possibilities for num-dis  

</details>  

</details>

## **Meeting 16/08/2024**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* Spatial learning - mitochondrial activity experiment completed  
* Numerical discrimination experiment completed  
* Associative and reversal learning manuscripts written, second one submitted  
* Prenatal GCs and learning meta-analysis screened  
 
</details>

<details>
  <summary style=font-size:16px>*Things to cover during meeting*</summary>

* Numerical discrimination analyses  
* Personal writing retreat 23-26/8  

</details>

<details>

  <summary style=font-size:16px>*What to do next two weeks*</summary>

* Finish numerical discrimination analyses  
* Write first numerical discrimination draft (planned due date: 27/8)  
* IF we hear back from _Animal Behaviour_:
  + Review manuscript and resubmit
  + Send associative learning manuscript to collaborators
* ELSE:
  + Extract Methods from papers meta-analysis
  + Video-analyses of prey discrimination experiment

</details>  

<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Prey discrimination experiment**  
  + (Proper) Video-analyses  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses (SEM?)  
  + Write Intro, Results, and Discussion  
* **Spatial learning task**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses (SEM?)  
  + Write Intro, Results, and Discussion  
* **Meta-analysis**  
  + Extract methods paper (better selection)  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses  
  + Write Intro, Methods, Results, and Discussion  
* **Meta-analysis Patrice**
  + Help with screening and extracting data
* **Effect of acute and chronical stress**  
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses  
  + Write Intro, Methods, Results, and Discussion
* **Personality**
  + (Proper) Video-analyses
  + Statistial analyses
  + Write Intro, Results, and Discussion
* **Personality (Fonti)**
  + Video-analyses
  + Statistial analyses
  + Write Intro, Methods(?), Results, and Discussion  
  
</details>  

</details>

## **Meeting 02/09/2024**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Finish numerical discrimination analyses~~  
* ~~Write first numerical discrimination draft (planned due date: 27/8)~~  
* IF we hear back from _Animal Behaviour_:
  + Review manuscript and resubmit
  + ~~Send associative learning manuscript to collaborators~~
* ELSE:
  + Extract Methods from papers meta-analysis
  + Video-analyses of prey discrimination experiment 
 
</details>

<details>
  <summary style=font-size:16px>*Things to cover during meeting*</summary>

Checks??

</details>

<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Review manuscript and resubmit  
* Screening abstracts for Patrice
* Extract Methods from papers meta-analysis  
* Video-analyses of prey discrimination experiment  

</details>  

<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Prey discrimination experiment**  
  + (Proper) Video-analyses  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses (SEM?)  
  + Write Intro, Results, and Discussion  
* **Spatial learning task**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses (SEM?)  
  + Write Intro, Results, and Discussion  
* **Meta-analysis**  
  + Extract methods paper (better selection)  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses  
  + Write Intro, Methods, Results, and Discussion  
* **Meta-analysis Patrice**
  + Help with screening and extracting data
* **Effect of acute and chronical stress**  
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses  
  + Write Intro, Methods, Results, and Discussion
* **Personality**
  + (Proper) Video-analyses
  + Statistial analyses
  + Write Intro, Results, and Discussion
* **Personality (Fonti)**
  + Video-analyses
  + Statistial analyses
  + Write Intro, Methods(?), Results, and Discussion  
  
</details>  

</details>

## **Meeting 09/09/2024**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Review manuscript and resubmit~~  
* ~~Screening abstracts for Patrice~~  
* Extract Methods from papers meta-analysis  
* Video-analyses of prey discrimination experiment  
 
</details>

<details>
  <summary style=font-size:16px>*Things to cover during meeting*</summary>

How to extract the Methods

</details>

<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Extract Methods from papers meta-analysis  
* Video-analyses of prey discrimination experiment  
* Review the Associative learning manuscript  

</details>  

<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Prey discrimination experiment**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses (SEM?)  
  + Write Intro, Results, and Discussion  
* **Spatial learning task**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses  
  + Write Intro, Results, and Discussion  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses  
  + Write Intro, Methods, Results, and Discussion  
* **Meta-analysis Patrice**
  + Help with screening and extracting data
* **Effect of acute and chronical stress**  
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses  
  + Write Intro, Methods, Results, and Discussion
* **Personality**
  + (Proper) Video-analyses
  + Statistial analyses
  + Write Intro, Results, and Discussion
* **Personality (Fonti)**
  + Video-analyses
  + Statistial analyses
  + Write Intro, Methods(?), Results, and Discussion  
  
</details>  

</details>

## **Meeting 16/09/2024**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~2nd draft Associative learning manuscript~~   
* Extract Methods from papers meta-analysis  
* Video-analyses of prey discrimination experiment   
 
</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Extract Methods from papers meta-analysis   
* Video-analyses of prey discrimination experiment   
* Review the Associative learning manuscript   

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Prey discrimination experiment**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses (SEM?)  
  + Write  
* **Spatial learning task**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write Intro, Methods, Results, and Discussion  
* **Meta-analysis Patrice**
  + Help with screening and extracting data  
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write Intro, Methods, Results, and Discussion  
* **Personality**
  + (Proper) Video-analyses  
  + Statistial analyses  
  + Write Intro, Results, and Discussion  
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistial analyses  
  + Write Intro, Methods(?), Results, and Discussion   
  
</details>  

</details>

## **Meeting 23/9/20024**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~2nd draft Numerical discrimination manuscript~~   
* Extract Methods from papers meta-analysis  
* Video-analyses of prey discrimination experiment   
 
</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

Associative learning manuscript

</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Extract Methods from papers meta-analysis   
* Video-analyses of prey discrimination experiment   
* Review the Associative learning manuscript   

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Prey discrimination experiment**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses (SEM?)  
  + Write  
* **Spatial learning task**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write Intro, Methods, Results, and Discussion  
* **Meta-analysis Patrice**
  + Help with screening and extracting data  
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write Intro, Methods, Results, and Discussion  
* **Personality**
  + (Proper) Video-analyses  
  + Statistial analyses  
  + Write Intro, Results, and Discussion  
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistial analyses  
  + Write Intro, Methods(?), Results, and Discussion   
  
</details>  

</details>

## **Meeting 11/11/2024**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~3rd draft Numerical discrimination manuscript~~     
* ~~Extract Methods from papers meta-analysis~~   
* ~~Final draft and submission of associative learning manuscript~~   
 
</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>


</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Numerical discrimination paper: final checkings and submission  
* EcoEvoRxiv website  
* Learning methodology: search for papers  
* Video-analyses of prey discrimination experiment   

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Prey discrimination experiment**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses (SEM?)  
  + Write  
* **Spatial learning task**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write Intro, Methods, Results, and Discussion  
* **Meta-analysis Patrice**
  + Help with screening and extracting data  
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write Intro, Methods, Results, and Discussion  
* **Personality**
  + (Proper) Video-analyses  
  + Statistial analyses  
  + Write Intro, Results, and Discussion  
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistial analyses  
  + Write Intro, Methods(?), Results, and Discussion   
  
</details>  

</details>

## **Meeting 18/11/2024**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Submit Numerical discrimination manuscript~~     
* ~~EcoEvoRxiv website~~   

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>


</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Extract data for Patrice's meta-analysis  
* Learning methodology: search for papers  
* Video-analyses of prey discrimination experiment   
* Lab??  

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **To learn or not to learn**  
  + Screen papers  
  + Extract data to see what is people doing  
  + Write  
* **Prey discrimination experiment**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses (SEM?)  
  + Write  
* **Spatial learning task**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Meta-analysis Patrice**
  + Help with screening and extracting data  
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistial analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistial analyses  
  + Write    
  
</details>  

</details>

## **Meeting 25/11/2024**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~HDR talk~~  
* ~~Extract data for Patrice's meta-analysis~~  
* ~~Learning methodology: search for papers~~  

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

* Learning methodology: search for papers  
  + Terms and what to include  
  + How to select manuscripts: ASReview? (see [Orr et al., 2024](https://onlinelibrary.wiley.com/doi/pdf/10.1111/ele.14463))  
* Other questions about data extraction?


</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Extract data for Patrice's meta-analysis  
* Learning methodology: get the appropiate papers  
* Video-analyses of prey discrimination experiment   
* Lab??  

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **To learn or not to learn**  
  + Screen papers  
  + Extract data to see what is people doing  
  + Write  
* **Prey discrimination experiment**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses (SEM?)  
  + Write  
* **Spatial learning task**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Meta-analysis Patrice**
  + Help with screening and extracting data  
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistial analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistial analyses  
  + Write    
  
</details>  

</details>

## **Meeting 02/12/2024**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Lab: DNA damage and lipid peroxidation in OB and OT~~  
* ~~Extract data for Patrice's meta-analysis~~  
* ~~Learning methodology: get the reference list and getting started with ASReview~~  

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

* Check 'learn or not to learn' process

</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Extract data for Patrice's meta-analysis  
* Learning methodology: screening  
* Video-analyses of prey discrimination experiment   
* Lab: DNA damage and lipid peroxidation in MC  

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **To learn or not to learn**  
  + Screen papers  
  + Extract data to see what is people doing  
  + Write  
* **Prey discrimination experiment**  
  + Statistical analyses (SEM?)  
  + Write  
* **Spatial learning task**  
  + Flow cytometry: DNA damage and lipid peroxidation  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistial analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistial analyses  
  + Write    
  
</details>  

</details>

## **Meeting 09/12/2024**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Lab: DNA damage and lipid peroxidation in MC~~  
* ~~Extract data for Patrice's meta-analysis~~  
* ~~Get ready df for Meta-CORT~~  

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>


</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Learning methodology: screening  
* Video-analyses of prey discrimination experiment   
* Start with extracting data for meta-analysis  

</details>  

<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **To learn or not to learn**  
  + Screen papers  
  + Extract data to see what is people doing  
  + Write  
* **Prey discrimination experiment**  
  + Statistical analyses (SEM?)  
  + Write  
* **Spatial learning task**  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistial analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistial analyses  
  + Write    
  
</details>  

</details>





## **Meeting 16/12/2024**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Learn how to extract flow data~~  
* ~~Extract data for Ondi's meta-analysis~~  
* ~~GC and learning: prepared the questions and data we got~~  
* ~~Organise READ ME files of submitted papers' repositories~~  
* ~~Videos of prey discrimination experiment~~  

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

* Check questions GC and learning meta-analysis  

</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Ondi's meta-analysis: finish extracting original papers  
* Learn or not to learn (learning methodology): screening   
* Video-analyses of prey discrimination experiment   
* Start with extracting data for meta-analysis   

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **To learn or not to learn**  
  + Extract data to see what is people doing  
  + Write  
* **Prey discrimination experiment**  
  + Validation experiment  
  + Statistical analyses (SEM?)  
  + Write  
* **Spatial learning task**  
  + Validation experiment  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistial analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistial analyses  
  + Write    
  
</details>  

</details>

## **Meeting 06/01/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Ondi's meta-analysis: finish extracting original papers~~    
* ~~Learn or not to learn (learning methodology): screening RAYYAN~~   
* Video-analyses of prey discrimination experiment   
* Methods Spatial learning  
* Methods Prey discrimination   

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>


</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Video-analyses of prey discrimination experiment   
* Methods Spatial learning  
* Methods Prey discrimination   
* Cell sorting validation experiment: email Mick   
* Finish validation experiment 'to learn or not to learn'  

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **To learn or not to learn**  
  + Extract data to see what is people doing  
  + Write  
* **Prey discrimination experiment**  
  + Statistical analyses (SEM?)  
  + Write  
* **Spatial learning task**  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistial analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistial analyses  
  + Write    
  
</details>  

</details>

## **Meeting 13/01/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Video-analyses of prey discrimination experiment~~   
* ~~Methods Spatial learning~~  
* ~~Methods Prey discrimination~~   
* ~~Cell sorting validation experiment: email Mick~~   

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>


</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Finish validation experiment 'to learn or not to learn'  
* Start Intro thesis   
* Sort lizards in mesocosmos: trim plants, put mulch, release old guys    
* Cell sorting validation experiment: plan experiment   


</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **To learn or not to learn**  
  + Write  
* **Prey discrimination experiment**  
  + Statistical analyses (SEM?)  
  + Write  
* **Spatial learning task**  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistical analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistical analyses  
  + Write    
  
</details>  

</details>

## **Meeting 20/01/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Tubs mesocosms~~   
* ~~Cell sorting validation experiment: first meeting~~   

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

Plans

</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Ondi's meta-analysis
* Finish validation experiment 'to learn or not to learn'  
* Sort lizards in mesocosmos: trim plants, release guys    
* Cell sorting validation experiment: induction, plan experiment   


</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **To learn or not to learn**  
  + Write  
* **Prey discrimination experiment**  
  + Statistical analyses (SEM?)  
  + Write  
* **Spatial learning task**  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistical analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistical analyses  
  + Write    
  
</details>  

</details>

## **Meeting 03/02/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* Ondi's meta-analysis
* Finish validation experiment 'to learn or not to learn'  
* Sort lizards in mesocosmos: trim plants, release guys    
* Cell sorting validation experiment: induction, plan experiment, get NeuN
* Start reading about SEM  

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>



</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Finish Ondi's meta-analysis
* Start screening experiment 'to learn or not to learn'  
* Sort lizards in mesocosmos: trim plants, release guys    
* Study SEM  


</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **To learn or not to learn**  
  + Write  
* **Prey discrimination experiment**  
  + Statistical analyses  
  + Write  
* **Spatial learning task**  
  + Statistical analyses  
  + Write  
* **Meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronical stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistical analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistical analyses  
  + Write    
  
</details>  

</details>

## **Meeting 17/02/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Ondi's meta-analysis~~
* ~~Start screening experiment 'to learn or not to learn'~~  
* ~~Sort lizards in mesocosmos: trim plants, release guys~~    
* ~~Study SEM~~  
* ~~Help Dalton with lizards' measurements~~
* ~~Start Prey Discrimination Analyses~~  
* ~~Work on learning and fitness meta-analisys~~

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

* Times/important dates thesis
* Models Prey-discr

</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Organise validation with CAM people/keep them posted
* Write Prey Discrimination: Results and Intro
* Continue screening experiment 'to learn or not to learn'
* Prepare validation of ASRev for 'learning and fitness' meta-analysis

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Thesis**
  + Write Introduction
  + Write Discussion/Conclusions
  + Compile all chapters
* **To learn or not to learn**  
  + Extract data (methods)
  + Write  
* **Spatial learning task**  
  + Statistical analyses  
  + Write  
* **CORT and learning meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronic stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistical analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistical analyses  
  + Write    
  
</details>  

</details>

## **Meeting 24/02/2025**

<details>
  <summary style=font-siz
  
  e:16px>*Things done since last meeting*</summary>

* ~~Organise validation with CAM people/keep them posted~~  
* ~~Write Prey Discrimination: Results and Intro~~  
* ~~Continue screening experiment 'to learn or not to learn'~~  
* ~~Validation of 'learning and fitness' meta-analysis~~  

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>


</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Write Prey Discrimination (first draft)  
* Start analysis of Spatial Learning chapter
* Continue screening experiment 'to learn or not to learn'  
* Second validation of 'learning and fitness' meta-analysis  

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Thesis**
  + Write Introduction
  + Write Discussion/Conclusions
  + Compile all chapters
* **To learn or not to learn**  
  + Extract data (methods)
  + Write  
* **Spatial learning task**  
  + Write  
* **CORT and learning meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronic stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistical analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistical analyses  
  + Write    
  
</details>  

## **Meeting 03/03/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Write Prey Discrimination: First draft~~  
* ~~Continue screening experiment 'to learn or not to learn'~~  
* ~~Validation of 'learning and fitness' meta-analysis~~  

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>
* Spatial learning analyses
* 'To learn and not to learn'

</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Start analysis of Spatial Learning chapter
* Continue screening experiment 'to learn or not to learn'  
* Second validation of 'learning and fitness' meta-analysis  

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Thesis**
  + Write Introduction
  + Write Discussion/Conclusions
  + Compile all chapters
* **To learn or not to learn**  
  + Extract data (methods)
  + Write  
* **Spatial learning task**  
  + Write  
* **CORT and learning meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronic stress**   
  + (Proper) Video-analyses  
  + Obtain faecal CORT (?) - Potential alternative: use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistical analyses  
  + Write   
* **Personality (Fonti)**  
  + Video-analyses  
  + Statistical analyses  
  + Write    
  
</details>  

</details>


</details>

## **Meeting 11/03/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Write Spatial learning intro, methods, and part of results~~  
* ~~Continue screening experiment 'to learn or not to learn'~~  
* ~~Validation of 'learning and fitness' meta-analysis~~  

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

* SEM
* Standardization of SD
* Slopes or general models for univariate models of learning

</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Finish writing Spatial Learning chapter  
* Continue screening experiment 'to learn or not to learn'  
* Submit the numerical discrimination review  

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Thesis**
  + Write Introduction
  + Write Discussion/Conclusions
  + Compile all chapters
* **To learn or not to learn**  
  + Extract data (methods)
  + Write  
* **CORT and learning meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronic stress**   
  + (Proper) Video-analyses  
  + ~~Obtain faecal CORT~~ - Use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistical analyses  
  + Write   
   
</details>  

</details>


</details>

## **Meeting 17/03/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Send spatial learning and prey discrimination papers~~  
* ~~Continue screening experiment 'to learn or not to learn'~~  
* ~~Validation of 'learning and fitness' meta-analysis~~  
* ~~Re-write the paper about numerical discrimination~~

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>


</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Validation of brain cells (if possible) / Start thesis Intro  
* Continue screening experiment 'to learn or not to learn'  
* Submit the numerical discrimination review  

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Thesis**
  + Write Discussion/Conclusions
  + Compile all chapters
* **To learn or not to learn**  
  + Extract data (methods)
  + Write  
* **CORT and learning meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronic stress**   
  + (Proper) Video-analyses  
  + ~~Obtain faecal CORT~~ - Use only behavioural data (anti-predatory behaviour?)  
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses  
  + Statistical analyses  
  + Write   
   
</details>  

</details>


</details>

## **Meeting 24/03/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Check and correct spatial learning paper~~    
* ~~Check and correct numerical discrimination paper~~   
* ~~Make ASAB poster~~   

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

- ASAB poster    
- Submissions     

</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Submit the 'intention of submission' form      
* Validation of brain cells  
* Start thesis Intro   
* Continue screening experiment 'to learn or not to learn'  
* Submit the numerical discrimination paper   
* Send spatial learning papers to collaborators    

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Thesis**
  + Write Discussion/Conclusions
  + Compile all chapters
* **To learn or not to learn**  
  + Extract data (methods)
  + Write  
* **CORT and learning meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronic stress**   
  + (Proper) Video-analyses   
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses   
  + Statistical analyses   
  + Write   
   
</details>  

</details>


</details>

## **Meeting 31/03/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Submit the 'intention of submission' form~~      
* ~~First draft thesis Intro~~   
* ~~Continue screening experiment 'to learn or not to learn'~~  
* ~~Submit the numerical discrimination paper~~   
* ~~Send spatial learning papers to collaborators~~  
* ~~Submit reviews Behavioral Ecology~~    

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

     
</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Validation of brain cells  
* Start thesis discussion   
* Teach Matheo to analyse the videos for 'Effect of acute and chronic stress'   
* Continue screening papers for 'to learn or not to learn'        

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Thesis**
  + Compile all chapters
* **To learn or not to learn**  
  + Extract data (methods)
  + Write  
* **CORT and learning meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronic stress**   
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses   
  + Statistical analyses   
  + Write   
   
</details>  

</details>


</details>

## **Meeting 26/05/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Validation of brain cells~~  
* ~~Thesis discussion~~   
* ~~Teach Matheo to analyse the videos for 'Effect of acute and chronic stress'~~   
* ~~Continue screening papers for 'to learn or not to learn'~~      

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

* Exit seminar   
* Thesis dates   
* Data mitochondrial activity    
     
</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Submit the form for the exit seminar   
* Check the plagiarism app and start report         
* Review intro and discussion    
* Review PreyD    
* Compile all chapters   
* Continue screening papers for 'to learn or not to learn'        

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **To learn or not to learn**  
  + Extract data (methods)
  + Write  
* **CORT and learning meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Effect of acute and chronic stress**   
  + Statistical analyses   
  + Write   
* **Personality**
  + (Proper) Video-analyses   
  + Statistical analyses   
  + Write   
   
</details>  

</details>


</details>

## **Meeting 04/06/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Submit the form for the exit seminar~~   
* ~~Do plagiarism report~~         
* ~~Review intro and discussion~~    
* ~~Review PreyD~~    
* ~~Help Mathéo with analyses~~   
* ~~Compile all chapters~~   
* Continue screening papers for 'to learn or not to learn'       

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

   
</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Exit seminar     
* Review PreyD    
* Submit JEB review    
* Review thesis (references, format, comments, etc.)    
* Continue screening papers for 'to learn or not to learn'        

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **Effect of acute and chronic stress**   
  + Statistical analyses   
  + Write   
* **CORT and learning meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **To learn or not to learn**  
  + Extract data (methods)   
  + Write  
* **Personality**
  + (Proper) Video-analyses   
  + Statistical analyses   
  + Write   
   
</details>  

</details>


</details>

## **Meeting 10/06/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Exit seminar~~   
* ~~Plagiarism report~~         
* ~~Help Mathéo with analyses~~   

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

* Results "stressor"
   
</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Write "stressor"         
* Review thesis (references, format, comments, etc.)    
* Continue screening papers for 'to learn or not to learn'        

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **CORT and learning meta-analysis**  
  + Meeting collaborators for data extraction  
  + Extract data papers  
  + Statistical analyses   
  + Write    
* **Learning and fitness**
  + Screening: maximize        
  + Screening     
  + Extract data             
* **To learn or not to learn**  
  + Extract data (methods)   
  + Write  
* **Personality**
  + (Proper) Video-analyses   
  + Statistical analyses   
  + Write   
   
</details>  

</details>


</details>


## **Meeting 01/07/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* Write "stressor"         
* ~~Review thesis (references, format, comments, etc.)~~    
* ~~Continue screening papers for 'to learn or not to learn'~~        
* ~~ASH and workshop~~

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>

* Organise earless dragon project            
* Rebuttal JEB            
* Podcast app?              
   
</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* Write and send "stressor"   
* CORT and learning meta-analysis: extract data          
* Learning and fitness: screening       
* Continue screening papers for 'to learn or not to learn'    
* Send JEB review         

</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **CORT and learning meta-analysis**  
  + Statistical analyses   
  + Write    
* **Learning and fitness**
  + Screening: maximize        
  + Screening     
  + Extract data             
* **To learn or not to learn**  
  + Extract data (methods)   
  + Write  
* **Personality**
  + (Proper) Video-analyses   
  + Statistical analyses   
  + Write   
   
</details>  

</details>


</details>

## **Meeting 21/07/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Send "stressor"~~         
* ~~Continue screening papers for 'to learn or not to learn'~~        
* ~~*Tympo's* lab~~   
* ~~Organise extraction prenatal CORT and learning meta-analysis~~               
* ~~Review JEB~~                

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>
             
   
</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* CORT and learning meta-analysis: extract data of 25 papers          
* Flow and more extractions *Tympos*          
* Continue screening papers for 'to learn or not to learn'     


</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **CORT and learning meta-analysis**  
  + Statistical analyses   
  + Write    
* **Learning and fitness**
  + Screening: maximize        
  + Screening     
  + Extract data             
* **To learn or not to learn**  
  + Extract data (methods)   
  + Write  
 
   
</details>  

</details>


</details>

## **Meeting 28/07/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Continue screening papers for 'to learn or not to learn'~~         
* ~~*Tympo's* lab~~       
* ~~CORT and learning meta-analysis: extract data of 10 papers~~            
* ~~Thesis review: Chs1-4~~           

</details>


<details>

  <summary style=font-size:16px>*Things to cover during meeting*</summary>
             
* *Tympos*     
* Numerical discrimination paper (what to do?)           
* When to re-submit             
* Take the computer               
* CORT-meta extraction: review              
   
</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* CORT and learning meta-analysis: have extracted 40 papers          
* Flow and more extractions *Tympos*          
* Continue screening papers for 'to learn or not to learn'      
* Thesis review: Ch5, Intro, and Discussion          


</details>  


<details>

  <summary style=font-size:16px>*Future to do list*</summary>

* **CORT and learning meta-analysis**  
  + Statistical analyses   
  + Write    
* **Learning and fitness**
  + Screening: maximize        
  + Screening     
  + Extract data             
* **To learn or not to learn**  
  + Extract data (methods)   
  + Write  
 
   
</details>  

</details>


</details>

## **Meeting 04/08/2025**

<details>
  <summary style=font-size:16px>*Things done since last meeting*</summary>

* ~~Continue screening papers for 'to learn or not to learn'~~         
* ~~*Tympo's* lab~~       
* ~~CORT and learning meta-analysis: extract data of 350 papers~~            
* ~~Thesis review~~           

</details>


<details>

  <summary style=font-size:16px>*What to do next week*</summary>

* ***Tympos***       
  + Finish the flow and analyse          
* **CORT and learning meta-analysis**  
  + Finish data extraction      
  + Statistical analyses   
  + Write    
* **Learning and fitness**
  + Screening: maximize        
  + Screening     
  + Extract data             
* **To learn or not to learn**  
  + Finish screening        
  + Extract data (methods)   
  + Write  
 
   
</details>  

</details>


</details>
