---
title: "Meta-analysis"
author: "Pablo Recio"
date: "`r Sys.Date()`"
output: 
    bookdown::html_document2: 
    code_folding: hide
    toc: yes
    toc_float: yes
    number_sections: no
editor_options: 
  chunk_output_type: console
---

<details>
  <summary style=font-size:20px>**Search terms**</summary>  

* Searchs made during 2022 in *Web of Science* and *Scopus*  
* Initial terms obtained from Eyck et al. 2019 (*Biol Rev*), and Lambert & Guillete 2021 (*Biol Rev*):  
  + developmental, early-life, pre-natal/hatch  
  + stress, maternal separation, handling, restrain, restriction, dessication, predator, hast hardening, nutrition, exposure, CORT, Glucocorticoids, Corticosterone  
  + cognition, learning, memory  

<font size=4.5>Code for *Web of Science*: </font>  

<details>
  <summary style=font-size:15px>*Trial 1*</summary>  
  
  - CODE: (development* OR early-life OR early life OR pre-natal* OR pre natal* pre-hatch* OR pre hatch* ) AND (stress* OR maternal separation OR handl* OR restr* OR dessicat* OR predat* OR nutrit* OR  expos* OR Glucocorticoid* OR Cort* ) AND (cognit* OR learn* OR memory) NOT (human* OR child* OR infant*)  
 - RESULTS: **55,602** papers  
</details>  

<details>
  <summary style=font-size:15px>*Trial 2*</summary>  
  
  - CODE: (eggs OR mother OR maternal OR early-life OR early life OR pre-natal* OR pre natal* OR pre-hatch* OR pre hatch* ) AND (stress* OR Glucocorticoid* OR Cort* ) AND (cognit* OR learn* OR memory) NOT (human* OR child* OR infant* OR therapy OR trauma* OR emotion* OR clinic* OR plant*)   
 - RESULTS: **3,214** papers  
</details>  

<font size=4.5>Code for *Scopus*: </font>  

<details>
  <summary style=font-size:15px>*Trial 1*</summary>  
  
  - CODE:  
    Search 1: TITLE-ABS-KEY(eggs OR mother OR maternal OR early-life OR "early life" OR pre-natal* OR "pre natal* " OR pre-hatch* OR "pre hatch* " AND NOT (human* OR child* OR infant* OR therapy OR trauma* OR emotion* OR clinic* OR plant*))  
    Search 2: TITLE-ABS-KEY(stress* OR Glucocorticoid* OR Cort* AND NOT (human* OR child* OR infant* OR therapy OR trauma* OR emotion* OR clinic* OR plant*))  
    Search 3: TITLE-ABS-KEY(cognit* OR learn* OR memory AND NOT (human* OR child* OR infant* OR therapy OR trauma* OR emotion* OR clinic* OR plant*))  
    Finally, I combined all the searches (Search > Search history > Combine queries) 
 - RESULTS: **1,528** papers  
</details>  

<details>
<summary><font size=4.5>*Other searches*: </font></summary>  
  
  Together with the search on both databases, I search those papers in the metadata from Eyck et al. 2019 (*Biol Rev*) where learning or cognition was measured as the main trait (**12** papers)
  
</details>  


</details>

<details>
<summary style=font-size:20px>**Papers downloaded and duplicated studies**</summary>

  * After obtaining all the references, I created a library on EndNote 20 (*Meta-analysis.enl*), combined all the references in one list and got rid of duplicates (Library>Find Duplicates).  
  Total number of duplicates: 931  
    - RESULTS: **4,288** papers  

</details>


<details>
<summary style=font-size:20px>**Rayyan process**</summary>

<details>
  <summary style=font-size:15px> How to import a library from NoteEnd </summary>  

  1. Export file from EndNote selecting **Output style 'Refman (RIS) Export'**
  2. Import to RAYYAN by using command **Select files**
 
</details>  

<details>
  <summary style=font-size:15px> How to share the RAYYAN library </summary>  
  
 
</details>

<details>
  <summary style=font-size:15px> How to get rid of papers </summary>  
  
 
</details>

<details>
  <summary style=font-size:15px> FINAL RESULTS </summary>  
  
 
</details>

</details>


<details>
<summary style=font-size:20px>**How to extract effect size**</summary>



</details>


<details>
<summary style=font-size:20px>**Analyses**</summary>



</details>




